// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.4
// source: chord.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// KeyServiceClient is the client API for KeyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KeyServiceClient interface {
	RPCLookup(ctx context.Context, in *Key, opts ...grpc.CallOption) (*ResponseNode, error)
	RPCRegisterNode(ctx context.Context, in *NodeIp, opts ...grpc.CallOption) (*NodeIp, error)
	RPCGetSuccessor(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NodeIp, error)
	RPCClosestPrecedingFinger(ctx context.Context, in *IdM, opts ...grpc.CallOption) (*NodeIp, error)
}

type keyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKeyServiceClient(cc grpc.ClientConnInterface) KeyServiceClient {
	return &keyServiceClient{cc}
}

func (c *keyServiceClient) RPCLookup(ctx context.Context, in *Key, opts ...grpc.CallOption) (*ResponseNode, error) {
	out := new(ResponseNode)
	err := c.cc.Invoke(ctx, "/chord.KeyService/RPCLookup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyServiceClient) RPCRegisterNode(ctx context.Context, in *NodeIp, opts ...grpc.CallOption) (*NodeIp, error) {
	out := new(NodeIp)
	err := c.cc.Invoke(ctx, "/chord.KeyService/RPCRegisterNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyServiceClient) RPCGetSuccessor(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NodeIp, error) {
	out := new(NodeIp)
	err := c.cc.Invoke(ctx, "/chord.KeyService/RPCGetSuccessor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyServiceClient) RPCClosestPrecedingFinger(ctx context.Context, in *IdM, opts ...grpc.CallOption) (*NodeIp, error) {
	out := new(NodeIp)
	err := c.cc.Invoke(ctx, "/chord.KeyService/RPCClosestPrecedingFinger", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeyServiceServer is the server API for KeyService service.
// All implementations must embed UnimplementedKeyServiceServer
// for forward compatibility
type KeyServiceServer interface {
	RPCLookup(context.Context, *Key) (*ResponseNode, error)
	RPCRegisterNode(context.Context, *NodeIp) (*NodeIp, error)
	RPCGetSuccessor(context.Context, *Empty) (*NodeIp, error)
	RPCClosestPrecedingFinger(context.Context, *IdM) (*NodeIp, error)
	mustEmbedUnimplementedKeyServiceServer()
}

// UnimplementedKeyServiceServer must be embedded to have forward compatible implementations.
type UnimplementedKeyServiceServer struct {
}

func (UnimplementedKeyServiceServer) RPCLookup(context.Context, *Key) (*ResponseNode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RPCLookup not implemented")
}
func (UnimplementedKeyServiceServer) RPCRegisterNode(context.Context, *NodeIp) (*NodeIp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RPCRegisterNode not implemented")
}
func (UnimplementedKeyServiceServer) RPCGetSuccessor(context.Context, *Empty) (*NodeIp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RPCGetSuccessor not implemented")
}
func (UnimplementedKeyServiceServer) RPCClosestPrecedingFinger(context.Context, *IdM) (*NodeIp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RPCClosestPrecedingFinger not implemented")
}
func (UnimplementedKeyServiceServer) mustEmbedUnimplementedKeyServiceServer() {}

// UnsafeKeyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeyServiceServer will
// result in compilation errors.
type UnsafeKeyServiceServer interface {
	mustEmbedUnimplementedKeyServiceServer()
}

func RegisterKeyServiceServer(s grpc.ServiceRegistrar, srv KeyServiceServer) {
	s.RegisterService(&KeyService_ServiceDesc, srv)
}

func _KeyService_RPCLookup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyServiceServer).RPCLookup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chord.KeyService/RPCLookup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyServiceServer).RPCLookup(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyService_RPCRegisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeIp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyServiceServer).RPCRegisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chord.KeyService/RPCRegisterNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyServiceServer).RPCRegisterNode(ctx, req.(*NodeIp))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyService_RPCGetSuccessor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyServiceServer).RPCGetSuccessor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chord.KeyService/RPCGetSuccessor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyServiceServer).RPCGetSuccessor(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyService_RPCClosestPrecedingFinger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdM)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyServiceServer).RPCClosestPrecedingFinger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chord.KeyService/RPCClosestPrecedingFinger",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyServiceServer).RPCClosestPrecedingFinger(ctx, req.(*IdM))
	}
	return interceptor(ctx, in, info, handler)
}

// KeyService_ServiceDesc is the grpc.ServiceDesc for KeyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KeyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chord.KeyService",
	HandlerType: (*KeyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RPCLookup",
			Handler:    _KeyService_RPCLookup_Handler,
		},
		{
			MethodName: "RPCRegisterNode",
			Handler:    _KeyService_RPCRegisterNode_Handler,
		},
		{
			MethodName: "RPCGetSuccessor",
			Handler:    _KeyService_RPCGetSuccessor_Handler,
		},
		{
			MethodName: "RPCClosestPrecedingFinger",
			Handler:    _KeyService_RPCClosestPrecedingFinger_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chord.proto",
}
